### ISSUE TITLE
Android: Add support for receiving notifications when app is closed

### ISSUE THREAD

**Issue by Topener** [williamrijksen/com.williamrijksen.onesignal#43]
To enable GCM receiver you need to add stuff to the manifest on android, as listed here: https://stackoverflow.com/questions/42694122/receive-notification-when-app-closed

However, since you need to specify a receiver class... this needs to be implemented I guess. Any ideas?

This also might be relevant https://stackoverflow.com/questions/24313539/push-notifications-when-app-is-closed

**Comment by jvandijk** [comment]
@Topener what is exactly the problem you experience? Did you already try to send a notification with high priority?

**Comment by Topener** [comment]
The not receiving notifications when app is closed/on phone restart, or is that fixed with high prio? Ti.Goosh does something similar

**Comment by jvandijk** [comment]
It's not about fixing.... it's about how Android handle's notifications. If you expect it the arrive realtime, you should use high priority because it will wake the device. If not... the notification will be presented when the phone gets out of Doze mode. See https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message

**Comment by Topener** [comment]
oh it is not about that. It is about when the device has rebooted or the app has been forced closed. Ti.Goosh still lets the phone receive notifications in that case (because it boots up on start and stuff). Yet there is nothing in the manifest for onesignal to support it
