### ISSUE TITLE
[iOS]The app closes at the beginning

### ISSUE THREAD

**Issue by iguane** [williamrijksen/com.williamrijksen.onesignal#51]
Good, I have a problem loading the module in titanium when the program runs in both the emulator and the device the app is closed, I'm using SDK 6.3.0 GA. Why can this happen? If I stop loading the module it does not close.

Thanks for your help

**Comment by williamrijksen** [comment]
@iguane which platform?

**Comment by iguane** [comment]
Appcelerator (Alloy)

**Comment by iguane** [comment]
For IOS

**Comment by iguane** [comment]
The same compilation on Android is working correctly

**Comment by chmiiller** [comment]
Hi @iguane because this is a bit old issue, I will be closing it for now, is that ok? I use to have this problem with app crashing in the beginning like you said, but it was a long time ago on older versions of the module. Maybe trying with a new one might fix your problem.
Please open a new issue in case this is not working for you, thanks!
