### ISSUE TITLE
Android Notification receive issue in latest devices

### ISSUE THREAD

**Issue by vishal95713** [williamrijksen/com.williamrijksen.onesignal#71]
I am using appcelerator, facing problem in receiving push notification in android oneplus 3 and above phones, also in Mi4i and many more phones with Oreo OS.
When app is in background or in foreground it receives notification, but when I remove app from my doc, then I am facing problem.

I got this error:-
broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.demo.notification (has extras) }

After looking over this, it shows that the service is been killed when you remove your app from doc list.
Kindly look after this issue it is very critical. Thanks in advance.

**Comment by adriendillens** [comment]
@vishal95713 @williamrijksen  I'm facing the same problem right now on : 
- Oneplus 5 (Android 8.1)
- Some Samsung (Android 8.0)

This doc tell us more about this issue : 
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

I do my best to fix this issue : 
- Update onesignal module with the latest Android SDK (from 3.8.0 to 3.10.1 thanks to @jordansilva)
- Added a channelId to all notifications (since Oreo doesn't display notification if not provided)
- Added REQUEST_IGNORE_BATTERY_OPTIMIZATIONS permission (which is granted by default, no user interaction needed)
- Check user settings (disable battery optimization & change notifications settings)

All of these changes doesn't solve issues...
Users receive notifications from other apps : snapchat, facebook, whatsapp, etc... (probably not using onesignal ?)

More and more users will update their Android OS version to 8 / 8.1
So in few weeks, this issue will be highly critical

@williamrijksen @chmiiller @jvandijk @ What can we do to solve it ?
We can't just wait for Android OS updates ...

**Comment by jvandijk** [comment]
@adriendillens could you test again with the latest release? https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.0

**Comment by chmiiller** [comment]
Closing this issue since it's almost 2 years old and it seems that's fixed already
